default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: bandwagon_development

test:
  <<: *default
  database: bandwagon_test

production:
  <<: *default
  database: bandwagon_production
  username: <%= ENV['POSTGRES_USER'] %> # optional if you have a specific user
  password: <%= ENV['POSTGRES_PASSWORD'] %> # optional
